kata-containers/documentation

- CODE_OF_CONDUCT.md
Add the standard code of conduct document.
Fixes #11.
> docs: Add code of conduct doc

- design/README.md
Fixes #13
Simply create the directory and put a README
> create directory for design documents

- README.md
Add some brief explanatory text and a few pointers.
Fixes #36.
> docs: Embellish README

- Developer-Guide.md
Add details of the collect script in under the "Troubleshoot" section.
Fixes #34.
> docs: Mention collect script in dev guide

- architecture.md
- Changed the header a bit to reflect the new CRI Plugin name
- Also, added more details in terms of similarities and arch related to CRI-O
> Added more details to the Containerd CRI Plugin

- Developer-Guide.md
add steps to build kata kernel from source
> developer-guide: update guest kernel image section

- install/README.md
> install: add installation readme

- install/README.md
Added more info the install README:
- introductory sentence.
- reformatted with bullets.
- developer guide and runtime repo links.
> Update install readme

- install/README.md
- install/centos-installation-guide.md
This will add the installation guide for CentOS.
Fixes #84
> docs: Add CentOS installation guide

- how-to/how-to-use-k8s-with-cri-containerd-and-kata.md
Add instructions how to create pods using kata and cri containerd plugin in a kueberentes setup.
> how-to: Use K8s "cri"  containerd  plugin and kata.

- Documentation-Requirements.md
Add details to documentation requirements document explaining how we use
and format notes.
Fixes #125.
> docs: Add notes to doc requirements

- architecture.md
- zun_kata.md
Correct invalid document URLs.
Fixes #149.
> docs: Fix invalid URLs

- README.md
- design/README.md
Many docs in this repo were not in the repo index.
Add them.
Also, update the design subdir index as well.
> README: Update documentation indexes

- constraints/cpu.md
Add CPU constraints documentation
fixes #136 
> constraints: document CPU constraints

- architecture.md
> docs: Add relevant URLs and fix grammar

- Developer-Guide.md
> dev-guide: Mention distro support for ppc64le for rootfs creation

- Documentation-Requirements.md
Update the documentation requirements on the topic of images.
Fixes #189.
> docs: Document image requirements

- Developer-Guide.md
Journald, by default on some systems, will rate limit log messages,
and in the case of our 'enable full debug', will likely drop some
of our debug.
Document how to identify if this is happening, and how to configure
`systemd-journald` appropriately.
Fixes: #181
> Dev: Document journald limitations and workarounds

- Documentation-Requirements.md
Explain how to handle filenames and command names in documentation.
Fixes #187.
> docs: Requirements for filenames and commands

- install/gce-installation-guide.md
> install: gce: show should be describe for image inspection

- install/docker/centos-docker-install.md
- install/docker/fedora-docker-install.md
- install/docker/rhel-docker-install.md
- install/docker/ubuntu-docker-install.md
Fixes: #484
Signed-off-by: Stefan Heitmüller <stefan.heitmueller@gmx.com>
> docs: add kata-runtime to Docker daemon.json

- Developer-Guide.md
Looks like the debug console socket location has moved. Update it.
Also minor grammatical fixups.
> Fix debug console socket docs

- install/README.md
- install/docker/opensuse-docker-install.md
- install/opensuse-installation-guide.md
This is the installation guide for OBS packages for
openSUSE.
Fixes #160
> docs: Add OBS package installation guide for openSUSE

- install/ubuntu-installation-guide.md
Include in the document the support for ubuntu 18.04.
Fixes #214
> docs: Update installation guide for Ubuntu.

- VSocks.md
Add vsock documentation
fixes #226
> usecases: add vsock documentation

- README.md
Ship more information of the documents in the README page.
Fixes: #244
> README.md: update the README of the documentation repo

- Limitations.md
update 'update command' section
fixes #248
> Limitations: update 'update command' section

- Release-Checklist.md
add snap packages to the release checklist
fixes #257
> checklist: add snap packages to the release checklist

- architecture.md
docs: Delete the wrong cni flow in README
Fix the wrong  Network CNI section.
Fixes: #287 
Signed-off-by: Liu Cimin <lcmjkson@gmail.com>
> docs: Delete the wrong cni flow in README

- architecture.md
Update the k8s create sandbox and container code in runtime.
Fixes #292
Signed-off-by: Liu Cimin lcmjkson@gmail.com
> docs: update the architecture doc

- install/README.md
- install/snap-installation-guide.md
Add snap installation guide
fixes #274
> install: add snap installation guide

- Developer-Guide.md
Only create a new docker unit file if no other existing unit files
are detected. Creating a new docker file when not necessary may mask out
existing docker daemon configurations.
Fixes: #300
> dev-guide: detect & use existing docker unit file

- VSocks.md
Add introduction about use kata containers with vsock inside VMWare guest.
Fixes: #326
Signed-off-by: Hui Zhu <teawater@hyper.sh>
> vsock: Add introduction about VMWare guest

- how-to/what-is-vm-templating-and-how-do-I-use-it.md
So that we have a doc to point to when people asks about VM templating.
Fixes: #347
> howto: add vm template introduction and guide

- install/ubuntu-installation-guide.md
> install: have ubuntu install point to master for 1.5 release

- install/README.md
add snap store banner
fixes #369
> snap: add snap store banner

- constraints/cpu.md
Explain cpu cgroups are implemented in kata containers
fixes #386
> constraints: add cpu cgroups documentation

- CODEOWNERS
Add a CODEOWNERS file so we get auto-review requests from github
for any .md file changes.
Fixes: #394
> ci: add a CODEOWNERS file to cover .md files

- how-to/what-is-vm-cache-and-how-do-I-use-it.md
- how-to/what-is-vm-templating-and-how-do-I-use-it.md
Add "What Is VMCache and How To Enable It" to howto.
Fixes: #392
Signed-off-by: Hui Zhu <teawater@hyper.sh>
> howto: Add VMCache introduction and guide

- install/debian-installation-guide.md
Fixes: #357
Signed-off-by: Yang Bo <bo@hyper.sh>
> install: VERSION_ID in buster/sid can be unset. default it to 9

- Developer-Guide.md
update architecture.md link, since it has moved to within the
design/ directory.
contributes to: #417
Signed-off-by: Gabi Beyer <Gabrielle.n.beyer@intel.com>
> doc: update architecture.md link

- use-cases/zun_kata.md
Fixes: #429
Add zun-ui plugin for devstack when intergrated with zun
Depends-on:github.com/kata-containers/tests#1484
Signed-off-by: Lei Xu <xulei@cmss.chinamobile.com>
> Zun: add zun-ui plugin for devstack

- README.md
Fixes: #431
GPU-Passthrough-with-Kata link to a error address.
Signed-off-by: Lei Xu <xulei@cmss.chinamobile.com>
> Update README.md for GPU-Passthrough-with-Kata

- README.md
correct the link of VM Templating
Signed-off-by: WangYu <WangYu@linux.alibaba.com>
> README: Update README.md for link of VM Templating

- Developer-Guide.md
Add how to get kata-containers/qemu and checkout to a proper version in developer-guide
Fixes: #437
Signed-off-by: Lei Xu <xulei@cmss.chinamobile.com>
> Docs: update Build-a-custom-QEMU in Developer-Guide

- how-to/containerd-kata.md
update the link of shimv2.svg
Fixes: #440
Signed-off-by: Lei Xu <xulei@cmss.chinamobile.com>
> Docs: Update link in containerd-kata.md

- install/rhel-installation-guide.md
RHEL now is being part of the CI.
Fixes #415
> docs: Update RHEL documentation

- .travis.yml
Enable travis on ppc64le
Fixes:  #479
> documentation: Add travis CI for ppc64le

- Developer-Guide.md
- Documentation-Requirements.md
- Limitations.md
- Release-Checklist.md
- Stable-Branch-Strategy.md
- Upgrading.md
- design/VSocks.md
- design/architecture.md
- design/cpu-constraints.md
- design/kata-api-design.md
- how-to/containerd-kata.md
- how-to/how-to-use-k8s-with-cri-containerd-and-kata.md
- how-to/how-to-use-sysctls-with-kata.md
- how-to/how-to-use-virtio-fs-with-kata.md
- how-to/service-mesh.md
- how-to/what-is-vm-cache-and-how-do-I-use-it.md
- install/README.md
- install/aws-installation-guide.md
- install/docker/debian-docker-install.md
- install/gce-installation-guide.md
- use-cases/GPU-passthrough-and-Kata.md
- use-cases/using-SRIOV-and-kata.md
- use-cases/using-vpp-and-kata.md
- use-cases/zun_kata.md
Tidy up docs by resolving spelling mistakes and fixing bad formatting.
Fixes: #487.
> docs: Fix typos and formatting

- install/installing-with-kata-doc-to-script.md
- install/installing-with-kata-manager.md
- install/snap-installation-guide.md
Ensure all non-dictionary words are in backticks.
Fixes: #504.
> docs: Fix formatting

- .ci/setup.sh
- .travis.yml
- Documentation-Requirements.md
Add further advice to the documentation requirements document to make it easier for the spell checker to accept a document.
Fixes: #501.
> docs: Update doc requirements doc for spell checker

- design/architecture.md
Fix broken CRI Link. 
Fixes:  #521
> architecture.md: Fix broken CRI link

- Limitations.md
Note that docker compose has similar issues to docker swarm
when under Kata.
Fixes: #530
> Limitations: docker compose: note it has issues

- design/architecture.md
Update initrd placeholder. 
Fixes: #548
> architecture.md: Update initrd placeholder

- how-to/README.md
- how-to/how-to-use-kata-containers-with-acrn.md
- how-to/offline_cpu.sh
Start-up guide on setting up kata containers
with ACRN hypervisor.
Fixes: #535
Signed-off-by: Vijay Dhanraj <vijay.dhanraj@intel.com>
> doc: how-to on Kata Containers with ACRN hypervisor

- use-cases/using-Intel-QAT-and-kata.md
This fixes #516
Signed-off-by: Eric Adams <eric.adams@intel.com>
> Updated QAT instructions

- Developer-Guide.md
Add rootfs distro choices for debian, ubuntu, and suse.
Fixes: #556.
Signed-off-by: zhanghj.lc <zhanghj.lc@inspur.com>
> Developer-Guide.md: update rootfs build description

- how-to/README.md
- how-to/how-to-load-kernel-modules-with-kata.md
Add documentation describing how to load kernel modules with kata containers
fixes #563
> how-to: add how-to for loading kernel modules

- install/aws-installation-guide.md
- install/docker/centos-docker-install.md
- install/docker/debian-docker-install.md
- install/docker/fedora-docker-install.md
- install/docker/opensuse-docker-install.md
- install/docker/rhel-docker-install.md
- install/docker/sles-docker-install.md
- install/docker/ubuntu-docker-install.md
Unless ubuntu we have to actually create the `/etc/docker` folder before we write `/etc/docker/daemon.json` file.
Signed-off-by: shinebayar-g <shinebayar.gansukh@gmail.com>
> Fix centos docker installation docs.

- how-to/how-to-use-kata-containers-with-acrn.md
Update start-up guide on setting up kata containers with ACRN hypervisor.
Addresses 2 parts,
1. Fixes broken links.
2. Adds a pre-requisite to enable MACVTAP for networking
in the Service OS.
Fixes: #580
Signed-off-by: Vijay Dhanraj <vijay.dhanraj@intel.com>
> doc: update how-to on Kata Containers with ACRN hypervisor

- design/host-cgroups.md
update host-cgroups documentation according to the new changes in the runtime
fixes #588
> design: update host-cgroups documentation according to the new changes

- how-to/README.md
- how-to/how-to-use-virtio-mem-with-kata.md
Add how-to for Kata Containers with virtio-mem.
Fixes: #591
Signed-off-by: Hui Zhu <teawater@antfin.com>
> how-to: Add how-to for Kata Containers with virtio-mem

- design/host-cgroups.md
document what cgroups are supported and what changes are needed in the
configuration file to support them.
fixes #603
> design: document cgroups v1 and v2

- how-to/how-to-import-kata-logs-with-fluentd.md
shimv2/containerd logs are placed and formatted differently than for
kata CRI-O. Add some details to the Fluentd parsing document to aid
in parsing those.
Fixes: #610
> howto: fluentd: add details for shimv2

- how-to/README.md
- how-to/how-to-set-sandbox-config-kata.md
It explains the details of current supported annotations.
Fixes: #486
Fixes: #294
Signed-off-by: Peng Tao <bergwolf@hyper.sh>
> howto: add sandbox config annotation howto

- use-cases/using-SPDK-vhostuser-and-kata.md
Revision is required in this use-case document, in order to give user a clear explanation.
It targets for issue #626
> Revise use-case of Using-SPDK-vhostuser-and-kata.md

- install/sles-installation-guide.md
This PR updates the current version of the SLES obs packages that are
being generated.
Fixes #651
> doc: Fix SLES installation documentation

- install/minikube-installation-guide.md
Link has moved, update it.
Fixes #666
> docs: Update link for minikube kvm2 driver

- how-to/how-to-set-sandbox-config-kata.md
Document all the missing annotations that were added to kata in the past
months but were not documented here.
fixes #614
> how-to: update annotations

- design/architecture.md
Update directory about state and tap device's should be tap0_kata for architecture.md
Signed-off-by: duanquanfeng <duanquanfeng_yewu@cmss.chinamobile.com>
> docs: Update directory and change kata_tap0 to tap0_kata

- how-to/how-to-set-sandbox-config-kata.md
Document restricted annotations, as implemented in
https://github.com/kata-containers/runtime/pull/3005
Signed-off-by: Christophe de Dinechin <dinechin@redhat.com>
> docs: Document restricted annotations

- how-to/how-to-import-kata-logs-with-fluentd.md
- how-to/how-to-load-kernel-modules-with-kata.md
- how-to/how-to-set-sandbox-config-kata.md
- how-to/how-to-use-kata-containers-with-acrn.md
- how-to/how-to-use-virtio-mem-with-kata.md
- how-to/service-mesh.md
- install/docker/opensuse-leap-docker-install.md
- install/docker/opensuse-tumbleweed-docker-install.md
- install/installing-with-kata-doc-to-script.md
- install/opensuse-leap-installation-guide.md
- install/opensuse-tumbleweed-installation-guide.md
70b916f  docs: Add a link to document describing how to use annotations
ec20c08 docs: Document restricted annotations
> 1.12 annotation related backports

- install/snap-installation-guide.md
Improve snap documentation, document how to install
kata 1.x and 2.x, how to configure them and their integration
with container engines.
fixes #766
> install: Improve snap documentation

- how-to/how-to-import-kata-logs-with-fluentd.md
- how-to/how-to-set-sandbox-config-kata.md
- install/minikube-installation-guide.md
This brings fixes from #773, #765, #758, and #682.
> docs:  A merge of the stale PRs.
