- .pullapprove.yml
Require two approvals from documentation team members before a PR
can land.
The configuration file is the same as those used for the other repos,
except for the approval team name.
Fixes #2.
> CI: Enable pullapprove

- design/kata-design-requirements.md
Adding initial kata requirements list, based off of discussion from
kata-containers/runtime issue #31.
> requirements: add initial document

- Developer-Guide.md
Move the developer guide from the wiki "in-tree".
Fixes #29.
> docs: Add developer guide

- design/kata-api-design.md
To fulfill the [kata design requirements](kata-design-requirements.md), and based on the disscusion on [Virtcontainers API extentions](https://docs.google.com/presentation/d/1dbGrD1h9cpuqAPooiEgtiwWDGCYhVPdatq7owsKHDEQ), [runtime API early sketch](https://github.com/kata-containers/runtime/pull/32) and [runtime API comparison](https://github.com/kata-containers/runtime/issues/46), the PR added the high level design of the kata runtime library API.
Fixes: #26
> design: add api design doc

- Developer-Guide.md
Change the command to enable agent debug slightly so that even if the
config file specifies kernel parameters, the command will successfully
enable the agent debug.
Fixes #38.
> docs: Improve command to enable agent debug

- Developer-Guide.md
The table of contents showed an incorrect link for building and
installing the runtime.
Fixes #40.
> docs: Fix runtime link in dev guide

- Developer-Guide.md
Optionally, one can build an initrd image and configure kata runtime
to use it.
Fixes: #44
> dev-guide: add guide to build and setup initrd image

- Developer-Guide.md
If kata-runtime is already added as a runtime to kata-containers.conf 
then you need not add it again.  This is helful when we redo some
of the earlier steps and endup updating docker config again resulting 
in multiple "--add-runtime kata-runtime=.." which furthur results in failure 
in docker restart. 
Fixes #49
> dev-guide: Conditionally add kata-runtime as suffix

- Developer-Guide.md
Fix minor typos in the development guide.
Fixes #53
> dev-guide: Fix minor typos

- Limitations.md
- README.md
Add the list of known limitations.
Fixes #31.
> Add limitations doc

- Licensing-strategy.md
Add a brief document explaining that the project uses SPDX license
identifiers.
Fixes #58.
> docs: Add license strategy doc

- Release-Checklist.md
- Releases.md
Add a document providing an overview of releases along with the
all-important release checklist.
Fixes #32.
> docs: Add Release process docs

- install/ubuntu-installation-guide.md
Add ubuntu installation guide for kata containers packages.
Fixes #60
> docs: Add ubuntu installation guide

- Releases.md
The link to the release checklist in the Releases document was linking
to the parent document, not the separate checklist document.
Fixes #73.
> docs: Fix release checklist link in releases doc

- Developer-Guide.md
Add details to the developer guide of how to obtain a backtrace by
sending a `SIGUSR1` signal to the component.
Fixes #70.
> docs: Explain SIGUSR1 usage in dev guide

- Developer-Guide.md
Add details of how to install the packaged components to start off with
a working system. This involved splitting out part of the "Assumptions"
section into a new "Initial setup" section.
Fixes #80.
> docs: Update dev guide for OBS packages

- Developer-Guide.md
Add an appendix explaining how to setup a debug console to login to the
virtual machine for debugging.
Fixes #72.
> docs: Add debug console to dev guide

- Upgrading.md
Add a document explaining how to upgrade a system:
- Running Clear Containers.
- Already installed with Kata Containers binaries.
Fixes #78.
> docs: Add upgrading doc

- install/fedora-installation-guide.md
- install/ubuntu-installation-guide.md
Change the installation guides so that all commands the user must type
use an explicit bash code block rather than a standard code block.
This adds meaning to the documents and will then allow us to extract
the commands and run them for testing purposes.
Fixes #92.
> docs: Change install guides to use bash code blocks

- install/fedora-installation-guide.md
- install/ubuntu-installation-guide.md
> install: Fix kata installation steps.

- .ci/lib.sh
- .ci/run.sh
- .ci/static-checks.sh
- .travis.yml
Create a basic set of CI scripts that just run the static checks for
now.
Fixes #101.
> CI: Add CI scripts

- Limitations.md
cli events is now partly supported.It returns
the stats of a certain container.
OOM notification and Intel RDT stats are not supproted
as what runc does
Fixes: #103
Signed-off-by: Haomin <caihaomin@huawei.com>
> doc: change limitation doc for cli events

- install/fedora-installation-guide.md
- install/ubuntu-installation-guide.md
Remove the `bash` tag from the last command in the install guides where
we show the user how to create a container with a busybox shell. This
doesn't change the content of the document but it ensures that all bash
blocks can be run non-interactively (by the `kata-doc-to-script.sh`
script in the tests repo).
Fixes #109.
> docs: Ensure install doc bash commands are non-interactive

- install/centos-installation-guide.md
Remove backslash from centos url that was
preventing the $VERSION_ID to take its correct value.
Fixes: #112.
Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>
> install: Fix centos obs url

- Developer-Guide.md
Now that we have a README for the installation guides, update the
developer guide to refer to that page, to avoid hard-coding links to
(some of) the installation guides.
Fixes #117.
> docs: Make devguide refer to install README

- install/centos-installation-guide.md
The CentOS install guide was referencing an invalid package
(`dnf-plugins-core`) so update for the yum equivalent.
Fixes #329.
> docs: Fix CentOS install guide

- Documentation-Requirements.md
Add a document that explains the expectations for project
documentation.
Fixes #99.
> docs: Add a doc requirements doc

- Upgrading.md
runV and Kata Containers can live together but we need to make it clear
in the doc.
Fixes: #97
> upgrade: add runv upgrade guide

- install/README.md
- install/centos-installation-guide.md
- install/fedora-installation-guide.md
- install/ubuntu-installation-guide.md
- Make the leading Note in the install guides use the standard note formatting.
- Update the install guides to explain that packages are currently only available on x86_64.
- Update the install README and the install guides to point to the upgrading document.
- Add fullstops at the of bullets in install README.
Fixes #119.
> Add links to upgrade doc

- Upgrading.md
Hit below error when upgrading on Ubuntu:
The following packages have unmet dependencies:
kata-runtime : Depends: kata-ksm-throttler (>= 1.0.0+git.422c7f7-28)
but it is not going to be installed
Fix it by:
sudo dpkg -P cc-ksm-throttler
Signed-off-by: Liu Changcheng <changcheng.liu@intel.com>
> Ubunut/Kata: upgrade from clear container to kata container

- .ci/setup.sh
- .ci/test-install-docs.sh
- .travis.yml
Moved static tests to CI setup script and added a new CI test to execute
all install guides if any one changes.
Fixes #132.
> CI: test installation guides

- install/README.md
Puts the nested virt/bare metal requirement in the top line
of the Install Guide and references the Kata hardware
check.
Signed-off-by: Anne Bertucio <anne@openstack.org>
> docs: Adds hardware requirements to Install Guide

- Developer-Guide.md
Make "Install guest kernel images" in Developer-Guide
arch specific.
Fixes: #140
> docs: Make "Install guest kernel images" arch-sensitive

- .ci/test-install-docs.sh
- .travis.yml
- install/centos-installation-guide.md
- install/docker/centos-docker-install.md
- install/docker/fedora-docker-install.md
- install/docker/ubuntu-docker-install.md
- install/fedora-installation-guide.md
- install/ubuntu-installation-guide.md
The install guides assumed that users wanted to install Docker. Since there are other container managers, split the Docker-specific instructions into separate documents (with backlinks) and allow the user to choose between Docker or Kubernetes from the install guides.
Also, ensure the first mention of all the distro names in the install guides:
- Have the required asterisk after the name.
- Have a link to the website.
Fixes #144.
> docs: Split docker install into separate docs

- Developer-Guide.md
kernel_arch was being set to amd64 instead of x86_64
on intel. The kernel config file name starts with
x86_64 and hence this needs to be fixed.
Fixes:  #158
>  developer-guide: use the correct kernel config file name

- use-cases/using-SRIOV-and-kata.md
Add instructions for using SR-IOV enabled nic with Kata.
> sriov: Add instructions on using SR-IOV with Kata

- install/gce-installation-guide.md
This covers the GCP portion of #130.
Introduces a guide to configuring a VM image with nested virtualization. The
primary focus of the guide is the set of commands required for creating and
managing nested VMX GCE images. For Kata installation itself the guide defers
to the distribution-specific Kata documentation for actually installing Kata.
The upside is that it needn't be updated every time the instructions for a
given distribution change. The downside is that it is not a standalone
artifact.
Signed-off-by: Jon Olson <jonolson@google.com>
> docs: Add GCE installation guide.

- .ci/test-install-docs.sh
- install/docker/centos-docker-install.md
- install/docker/fedora-docker-install.md
- install/docker/rhel-docker-install.md
- install/docker/ubuntu-docker-install.md
The docker install guides end with a call to `docker run`. However, they
all specify `-ti` which is causing our CI to fail.
Remove the `-ti` so that the command works both under the CI and as
expected for the user.
Fixes #175.
> docs: Remove "-ti" from docker invocations

- .ci/lib.sh
Now static-checks.sh needs to have the
repository name as arguments.
Fixes #179.
Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>
> CI: update static-checks.sh call

- svc-mesh/service-mesh.md
This commit introduces the intructions to be able to run trendy
service mesh Istio and Conduit with Kata Containers. It provides
a bit of feedback on how they actually work to give the reader a
quick overview. After this introduction, it provides restrictions
and instructions to enable them with Kata Containers.
Fixes #171
Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>
> docs: svc-mesh: Create some documentation about service mesh

- install/README.md
- install/gce-installation-guide.md
Add the new Google Compute Engine installation guide to the installation README.
Also,
- Add a table of contents to the Google Compute Engine install guide.
- Simplify the installation README by using relative URLs - let github expand them automatically for readers.
Fixes #173.
> GCE tweaks

- install/centos-installation-guide.md
- install/fedora-installation-guide.md
- install/rhel-installation-guide.md
- install/ubuntu-installation-guide.md
The anchor changed for Kube get started instructions. Updated the installation guides to correct the developer guide links.
Fixes https://github.com/kata-containers/documentation/issues/184
> docs: update kube anchor in distro install guides

- Developer-Guide.md
https://github.com/kata-containers/runtime/pull/527 Removed the
hard-coded `initcall_debug` kernel option (as it generates a lot of
kernel output at boot).
Add the `initcall_debug` option to the "Enable full debug" section to
allow users to enable these potentially useful messages when debugging.
Fixes #204.
> docs: Add initcall_debug to dev guide debug section

- Developer-Guide.md
The kernel config file name prefix changed from
ppc64le to powerpc. This change broke the kernel
build on ppc64le. Fix the kernel build steps
accordingly.
Fixes: #207
> Dev-guide: Kernel build fails on ppc64le

- architecture.md
Since there have not been any major architecture changes
in Kata Containers since 1.0 release, bump version to latest 
1.2.0 release. Also, add another supported machine type 
"pseries" for IBM Power Systems. A typo is also fixed in this
commit. 
Fixes #210
> architecture.md: Bump Kata Version to 1.2.0, add pseries info.

- install/ubuntu-installation-guide.md
Remove the support of ubuntu 17.10 as it is now end of life.
Fixes #223
> docs: Remove support of ubuntu 17.10 on installation guide

- install/sles-installation-guide.md
Now that this issue has solved kata-containers/packaging#39,
we can remove the workaround for the proxy and the shim.
Fixes #216
> docs: Remove workaround on SLES install documentation

- install/fedora-installation-guide.md
Update install documentation guide for fedora to include the
support for fedora 28.
Fixes #218
> docs: Update install guide for fedora

- use-cases/using-vpp-and-kata.md
this PR creates a use-cases subdirectory and adds an initial use case,
booting a kata container which makes use of vpp vhost-user interface.
Going forward, will add similar documents for SRIOV support, vhost-user-scsi / SPDK, RDMA, QAT, etc.
This starts to address https://github.com/kata-containers/documentation/issues/22
> use-cases: add VPP directions

- install/README.md
The "OpenSuse" link under "Installing Kata Containers"
is broken. Fix it.
Fixes: #228
> documentation:install: Fix a broken link

- Developer-Guide.md
The minimum golang version should be defined *once* - in [1]. Since the
developer guide already provides a link to that human-readable file,
remove the hard-coded golang version number to avoid having to maintain
that part of the devguide.
Fixes #232.
[1] - https://github.com/kata-containers/runtime/blob/master/versions.yaml
> docs: Don't hardcode minimum golang version

- Limitations.md
issue https://github.com/kata-containers/runtime/issues/187 was fixed
fixes #239
> limitations: remove 'docker run and kernel memory' section

- Limitations.md
> Limitation: Document docker --security-opt option not supported

- install/README.md
- install/centos-installation-guide.md
- install/fedora-installation-guide.md
- install/opensuse-installation-guide.md
- install/rhel-installation-guide.md
- install/sles-installation-guide.md
- install/ubuntu-installation-guide.md
The repository URLs in the installation guides needs to point to the
latest release version.
This impact tests execution too (kata-manager uses this guides as
installation recipes).
Fixes: #255
> install: have URLs point to the latest version on OBS

- Limitations.md
We do not currently support enablement of `selinux` in the
dockerd config. Document that.
Fixes: #252
> Limitations: add selinux support limitation

- use-cases/GPU-passthrough-and-Kata.md
This document decsribes how an Intel GPU can be used with
Kata Containers in GVT-g and GVT-d mode.
An example of an actual workload will be added in the future.
Fixes #260
> use-cases: Add documentation for using Intel GPU with Kata

- Developer-Guide.md
evged is required to make Kata work with NEMU.
Apply the kernel patch when building kernel.
Fixes: #268
> Developer-Guide:  Update kernel installation doc

- install/README.md
- install/centos-installation-guide.md
- install/docker/centos-docker-install.md
- install/docker/fedora-docker-install.md
- install/docker/opensuse-docker-install.md
- install/docker/rhel-docker-install.md
- install/docker/sles-docker-install.md
- install/docker/ubuntu-docker-install.md
- install/fedora-installation-guide.md
- install/installing-with-kata-doc-to-script.md
- install/installing-with-kata-manager.md
- install/opensuse-installation-guide.md
- install/rhel-installation-guide.md
- install/sles-installation-guide.md
- install/ubuntu-installation-guide.md
Refactor installation instruction to minimize duplicate content,
to document package source verification process, and to remove
some of the typos.
Fixes: #263
> install: Refactor installation instructions

- install/installing-with-kata-manager.md
Use a one-line code block for the installation command, and document the
dry run option.
Fixes: #275
> install: clean instructions for kata-manager

- install/README.md
Improvements to the table in the installation README:
- Fix the invalid link for the "Build from sources" option.
- Add column for "Packaged install" to make it clearer which
options result in a distro-packed install.
- Tweaked the "Suggested for" column to make the use-case options
clearer.
- Added detail for each use-case in a "Description" column.
Also, added a little more information on the "Scripted Installation" section of the install README.
Fixes #276.
> docs: Improve table in install README

- .travis.yml
- Makefile
Travis appears to be providing a version of golang that is too old for
https://mvdan.cc/xurls/cmd/xurls, which is used by the CI scripts in the
tests repo.
See:
- https://github.com/kata-containers/runtime/pull/744
- https://github.com/kata-containers/tests/pull/843#issuecomment-432297737
Fixes #281.
> CI: Pin Travis golang version

- .ci/test-install-docs.sh
- install/installing-with-kata-doc-to-script.md
Add new CI tests to ensure that the following installation methods are
also tested:
- "Automatic" method ([`kata-manager`](https://github.com/kata-containers/tests/tree/master/cmd/kata-manager))
- "Scripted" method ([`kata-doc-to-script`](https://github.com/kata-containers/tests/blob/master/.ci/kata-doc-to-script.sh))
**Note:** the "Automatic" method is **not** the same as the existing
`kata-manager` test: the existing test executes the "Manual"
installation method (which runs `kata-manager` to execute the
appropriate distro-specific install guide). However, this new test
executes the `install/installing-with-kata-manager.md` document, which
subsequently calls the `kata-manager` script.
Since the "Automatic" and "Scripted" installation methods are designed
to run "standalone" (without …
> CI: Test remaining install methods

- install/README.md
- install/aws-installation-guide.md
Installation guide for AWS.
cc: @annabellebertooch 
Signed-off-by: Ricardo Aravena <raravena@branch.io>
> install: Add AWS installation guide

- how-to/how-to-use-kata-containers-with-nemu.md
Instead of specifying a version for OVMF binary, this patch uses
a tiny script to retrieve the proper URL to download from.
Fixes #289
Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>
> nemu: Retrieve directly the latest OVMF binary

- Limitations.md
Now that https://github.com/kata-containers/runtime/pull/412 has been merged and
we have running a docker integration test for ramdisk in our CI
https://github.com/kata-containers/tests/pull/446, we can remove the limitation
of ramdisk.
Fixes #170
> docs: Remove Ramdisk Limitations

- Documentation-Requirements.md
Advise authors not to use continuation characters in code blocks.
Fixes #303.
> docs: Don't use backslashes in command blocks

- install/installing-with-kata-manager.md
Fix the link from #install-kata-packages-only to #install-the-kata-packages-only
> docs: fix a link in installing-with-kata-manager.md

- Developer-Guide.md
Signed-off-by: Johannes M. Scheuermann <joh.scheuer@gmail.com>
Correct the example in the developer docu otherwise you will get the following error:
```bash
error: error validating "nginx-untrusted.yaml": error validating data: ValidationError(Pod.spec.containers): invalid type for io.k8s.api.core.v1.PodSpec.containers: got "map", expected "array"; if you choose to ignore these errors, turn validation off with --validate=false
```
> Correct nginx example in developer docu

- Developer-Guide.md
- use-cases/using-SRIOV-and-kata.md
This improves the guest kernel build section of Developer-Guide
on arm64.
This also improve the description of sriov use-case.
Fixes: #299
Signed-off-by: Jia He <justin.he@arm.com>
> docs: Improve Developer-Guide and SRIOV doc on arm64

- install/README.md
The vexx got added as a '#' top level item instead of a
'*' bullet entry. Fix it...
Fixes: #316
> cloud: vexx: fix wrong style type of vexx title

- Documentation-Requirements.md
Document how other admonitions such as warnings and hints should be
handled.
Also includes a couple of other minor fixes.
Fixes #307.
> docs: Add warnings to doc requirements doc

- Developer-Guide.md
Since aarch64 need custom qemu binary and doesn't support OBS packaging for now, we add this section to lead developers to build required `qemu-system-aarch64` binary.
Fixes: #320
Signed-off-by: Penny Zheng <penny.zheng@arm.com>
> qemu: add 'Build a custom qemu-system-aarch64' section

- install/README.md
- install/debian-installation-guide.md
- install/docker/debian-docker-install.md
I have tested these install instructions in Debian 9.
Based on Ubuntu 17.10 packages with the main difference being that we need to pull `librdb1` from the unstable packages.
> Patch for debian install instructions docs

- Limitations.md
Document that seccomp support is now available. 
FIxes: #341
> Limitations: Remove seccomp limitation.

- Limitations.md
Hi @jodh-intel 
In a previous pull request https://github.com/kata-containers/documentation/pull/323 you proposed a different formatting of the commit message and to remove the network connect limitation.
> Docs: remove ps and network connect limitations

- install/snap-installation-guide.md
The snap install doc only told you how to install the kata snap,
and did not then go further to describe how to configure and
intergrate it. Those details are available already over in the
packaging repo, so let's link out to them.
Fixes: #360
> install: snap: add link out to config and integrate instrs

- install/debian-installation-guide.md
Although the installation instructions specify `apt-get -y ...`, the
installation blocks when trying to install the Kata pages with a message
like this:
```
...
Restart services during package upgrades without asking?
<Yes>                                          <No>
```
Setting `DEBIAN_FRONTEND=noninteractive` avoids this.
Fixes #363.
> install: Make Debian install fully non-interactive

- install/debian-installation-guide.md
Fix typo: librdbd1 -> librbd1 in install/debian-installation-guide.md
> docs: Fix typo

- README.md
We have some initial Firecracker/Kata documentaiton, but for now
it lives in the wiki. Link off to it from the top level docs
README to make it more obvious and easier to find.
Fixes: #367
> docs: firecracker: add top level link off to fc wiki page

- how-to/how-to-use-k8s-with-cri-containerd-and-kata.md
> docs: Fix a typo in how-to docs

- zun/zun_kata.md
Update zun guide to point to the kata installation instructions for
Ubuntu.
Fixes: #371
> zun: update kata install instructions

- architecture.md
Two links to `how-to` file is broken.
Fixes: #383
Signed-off-by: bin liu <liubin0329@gmail.com>
> docs: fix broken links in architecture.md

- .ci/test-install-docs.sh
- install/docker/centos-docker-install.md
- install/docker/debian-docker-install.md
- install/docker/fedora-docker-install.md
- install/docker/opensuse-docker-install.md
- install/docker/sles-docker-install.md
- install/docker/ubuntu-docker-install.md
Docker 18.09 removed devicemapper support but did not provide an
alternative. This can cause problems for users so update the install
docs to install Docker at version 18.06 (the last version that supports
devicemapper).
This is a temporary solution until either docker provide an alternative
or we find a way to work around the Docker feature being removed.
Fixes #373.
> docs: Pin docker to version 18.06

- install/rhel-installation-guide.md
- install/sles-installation-guide.md
Unfortunately, at present we have no way of testing Kata packages for Red Hat Enterprise Linux (RHEL) or SUSE Linux Enterprise (SLES).
Add warnings to the RHEL and SLES install guides explaining this and advising users to exercise caution. Hopefully, we will be able to drop this warning soon (either when we have the ability to test on RHEL/SLES or when Kata packages are available in RHEL/SLES).
Fixes #396.
> docs: Add RHEL and SLES install warnings

- how-to/containerd-kata.md
Update the how-to containerd-kata doc to support runtime option, by which
we can specify kata configure file for different kata runtime.
Fixes:#390
Signed-off-by: fupan <lifupan@gmail.com>
> how-to: Update the how-to containerd-kata doc to support runtime option

- README.md
- how-to/how-to-use-sysctls-with-kata.md
Document sysctls for Docker and Kubernetes.
> sysctsl: Add how-to doc for setting sysctls.

- README.md
Add links to all how-to and use-case docs in README.md so that they can be navigated to. Currently there is no way to reach them except actually browsing through the repo.
> Add links to all how-to and use-case docs in README.md

- Developer-Guide.md
The debug console systemd job needs to specify `PrivateDevices=no` to ensure the job can access the *real* console. Without this, connecting to the socket does not provide access to the main guest root context.
Also, since Kata supports multiple configuration file locations, update the dev guide to tweak config settings in `/etc/kata-containers/configuration.toml` rather than the pristine `/usr/share/defaults/kata-containers/configuration.toml` file. The former is read first meaning the system can be reset to a vanilla Kata configuration by simply deleting `/etc/kata-containers/configuration.toml`.
Fixes #403.
> Unbreak debug console instructions

- how-to/what-is-vm-cache-and-how-do-I-use-it.md
Remove vsock from VMCache howto because VMCache can work with vsock now.
Fixes: #405
Signed-off-by: Hui Zhu <teawater@hyper.sh>
> howto: Remove vsock from VMCache howto

- Developer-Guide.md
Change the debug console systemd job to specify the path to bash as `/bin/bash`, *not* `/usr/bin/bash`. This unbreaks the debug console for Ubuntu and Debian and also works for all other distros.
Fixes #410.
> docs: Fix debug console for ubuntu/debian

- Limitations.md
Kata does support privileged flag but within the guest,
so explain how this works in the Limitations docs.
Fixes #362
> Limitations: Remove privileged flag limitation

- .ci/test-install-docs.sh
- install/docker/centos-docker-install.md
- install/docker/debian-docker-install.md
- install/docker/fedora-docker-install.md
- install/docker/opensuse-docker-install.md
- install/docker/rhel-docker-install.md
- install/docker/sles-docker-install.md
- install/docker/ubuntu-docker-install.md
Don't force Docker to be kept at version 18.06 (to ensure devicemapper is available). This feature won't be re-added by Docker and remaining on an old version of Docker is not good from a security perspective.
Replace the pinning with a note pointing users at an issue which provides details of alternatives to devicemapper.
Fixes #407.
> Undo docker pin

- Developer-Guide.md
Add a note to the developer guide explaining that the debug console requires systemd support (hence nominally you cannot use alpine linux for example as that doesn't use systemd).
Fixes #412.
> docs: Explain systemd needed for debug console

- install/sles-installation-guide.md
Remove the warning as a CI of SLES in available
https://github.com/kata-containers/ci/pull/142.
Fixes #425
> doc: Update SLES installation documentation

- install/debian-installation-guide.md
- install/docker/centos-docker-install.md
- install/docker/debian-docker-install.md
- install/docker/fedora-docker-install.md
- install/docker/rhel-docker-install.md
- install/docker/sles-docker-install.md
- install/docker/ubuntu-docker-install.md
- install/ubuntu-installation-guide.md
Fix installing docker on Debian by changing the docker install guide to ensure that only the `kata-containers.conf` systemd service snippet is created. Previously, both the snippet and the `daemon.json` Docker config files were being updated because the latter also specified a bash code block.
Note that the `daemon.json` section is now consistent with the other install guides - it just displays the JSON code to add rather than trying to set it.
Also, added missing shell prompts, changed code blocks into shell (but not bash) code blocks and fixed a few minor grammar and whitespace issues across all install guides.
For further details, see:
- https://github.com/kata-containers/documentation/blob/master/Documentation-Requirements.md
- …
> Fix debian docker install

- Limitations.md
Remove the link of ps command from Limitations document.
Fixes #324
> docs: Remove ps command from Limitations

- Limitations.md
See https://github.com/kata-containers/runtime/issues/1568
> docs: Clarify security boundaries in privileged mode 

- Limitations.md
Fixed typo in table of contents link name which broke the link.
Fixes #456.
> docs: Fix incorrect link in limitations TOC

- Documentation-Requirements.md
- Add a new "Linking advice" section to the documentation requirements document.
- State that all documents should contain a table of contents.
Fixes: #458.
> Improve doc requirements

- how-to/how-to-use-k8s-with-cri-containerd-and-kata.md
remove `--skip-preflight-checks` option since it has been deprecated
fixes #460
> how-to: fix kubadm command

- how-to/containerd-kata.md
It's a little complicated to understand the note of the section
`Install containerd with cri plugin`, that says `Just check if the cri plugin
has been disabled in the containerd configuration file` but if it's disabled
containerd + the runtime class won't work.
fixes #462
> how-to: Fix `Install containerd with cri plugin` note

- how-to/how-to-use-virtio-fs-with-kata.md
virtio-fs has landed as an experimental feature in kata. This patch
enable the basic how-to for this feature.
Fixes: #468
Signed-off-by: Ganesh Maharaj Mahalingam <ganesh.mahalingam@intel.com>
> how-to: virtio-fs initial documentation

- Documentation-Requirements.md
New documentation is great, but finding it should be easy. Require that all new docs are referenced by an existing document in the repo.
Fixes #475.
> docs: Require all new docs to be referenced

- Documentation-Requirements.md
If a doc contains commands, they should be non-interactive where possible to allow for the possibility of automating the testing of the document in the CI.
Fixes #477.
> docs: Advise use of non-interactive commands

- install/README.md
- install/docker/opensuse-docker-install.md
- install/docker/opensuse-leap-docker-install.md
- install/docker/opensuse-tumbleweed-docker-install.md
- install/opensuse-installation-guide.md
- install/opensuse-leap-installation-guide.md
- install/opensuse-tumbleweed-installation-guide.md
Support installing kata packages on all openSUSE distros.
Fixes: #483
And also:
install: improve Docker installation for openSUSE
Editing systemd unit files to customize Docker for Kata may generate conflicts
with what's specified in /etc/sysconfig/docker, so use that file directly.
Also, libcgroup1 dependency is wrong for newer distros, and should be
pulled automatically for older ones.
> install: better support for all openSUSE distros

- Developer-Guide.md
This package is not installed with systemd in Clear. Add this
as an additional package requirement for debug console to make it
possible to debug.
This package contains utilties like `cat`, `ls`, `echo` etc required
for a useful debug.
Fixes #302
> debug: Add coreutils to the list of packages for debug console.

- design/cpu-constraints.md
The formula is not updated according on
how is done in kata-runtime.
Fixes: #489
Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>
> docs: cpu: resources: fix vcpu calculation formula

- README.md
Add a link to the newly-discovered source repository [1] for the Kata website [2] to allow users to raise issues and PRs on the website itself.
---
[1] - https://github.com/OpenStackweb/kata-netlify-refresh
[2] - https://katacontainers.io
Fixes: #497.
> docs: Add link to website source repo

- Developer-Guide.md
Update the developer guide with instructions to
attach to the debug console of a initrd rootfs based
VM. 
Fixes:  #502
> Dev Guide: Update with debug console for initrd

- Developer-Guide.md
Use 4.19.x config file when building kernel. 
Fixes: #507
> docs: Use kernel build script for building kernel in developer guide

- README.md
- use-cases/using-Intel-QAT-and-kata.md
These instructions cover how to install the out of tree
QAT drivers to the host, build a custom kata kernel and
rootfs, and build a QAT accelerated OpenSSL container
image.
Fixes: #509
> QAT: Add initial Intel QAT Kata instructions

- install/README.md
- install/minikube-installation-guide.md
Add a doc on how to setup and install Kata into Minikube.
> install: Add minikube instructions

- design/architecture.md
The networking part of the doc talks about the 
two ends of the veth pair. One end is in the container
networking namespace and the other one should
be in the host networking namespace. Fix this info.
Fixes: #518
> architecture.md: Fix networking info

- how-to/containerd-kata.md
In the workaround solution of ConfigPath, there is a '$@'
missing in the script, so add it.
Fixes: #515
Signed-off-by: Chengguang Xu <cgxu519@zoho.com.cn>
> docs: Fix workaround solution for ConfigPath

- install/debian-installation-guide.md
Once that https://github.com/kata-containers/tests/pull/1767 lands,
we can remove from the installation guide the steps of adding the
librbd1 repository.
Fixes #511
> docs: Fix debian installation guide

- install/minikube-installation-guide.md
`kata-fc` does not presently function under `minikube` due to
lack of block based storage. Make that clear in the installation
documents, to help prevent users going through the whole install
process, only to be disappointed when they find ti does not work.
Fixes: #526
> minikube: note kata-fc does not function under minikube

- install/README.md
Remove support/installation information for fedora 27, and
add fedora 30.
Fixes: #528
Signed-off-by: gabi beyer <gabrielle.n.beyer@intel.com>
> Update fedora version support

- install/README.md
Refresh installation guide README with a clearer structure, and provide
a list of distribution with official Kata packages. This also updates
the openSUSE Leap versions supported to 15 and 15.1.
Fixes: #533
> install: refresh installation guide README

- how-to/containerd-kata.md
Running the container with `ctr` when the image is not present
on the system gives an error.
Fixes #536
> shimv2: Add instruction to pull image first

- how-to/how-to-use-virtio-fs-with-kata.md
The documentation says hugepages are required for virtio-fs.  This
limitation was removed in Kata 1.8 in kata-runtime commit
a41894da18310b9c14dd59da1e924f4938271d4f ("runtime: Enable file based
backend").
Fixes: #544
Signed-off-by: Stefan Hajnoczi <stefanha@gmail.com>
> virtiofs: hugepages is no longer required since Kata 1.8

- Limitations.md
- how-to/README.md
- how-to/privileged.md
This commit adds documentation for privileged containers and the mounting of host devices
when privileged is used. It has instructions for disabling this functionality when using
Containerd and CRI.
Signed-off-by: Alex Price <aprice@atlassian.com>
> docs: add documentation for privileged and host devices

- Developer-Guide.md
- how-to/README.md
- how-to/run-kata-with-k8s.md
k8s how-to: rewrite intro and introduce cri-o RuntimeClass
Update the k8s Kata guide introduction, and specify RuntimeClass option
for CRI-O 1.12+.
how-to: improve landing README.md
Improve landing README.md by categorizing howto guides.
how-to: move k8s guide into a dedicate how-to md
Create a dedicate how-to guide for running Kata with k8s, and link to it
from the original guide location inside the Developer Guide.
Fixes: #333
> how-to: move k8s guide into a dedicate how-to md

- Limitations.md
- design/README.md
- design/VSocks.md
- design/host-cgroups.md
- design/vcpu-handling.md
Document how cgroups are done today and what is expected
for the upcoming SandboxCgroupOnly option.
Prior cgroup documentation are no longer accurate. Removing the cgroup
discussion from the cpu sizing discussion. Updating the
cpu-constraints.md file name to reflect this.
Fixes: #542
Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>
> docs: Add documentation about host cgroup management

- install/docker/centos-docker-install.md
- install/docker/debian-docker-install.md
- install/docker/fedora-docker-install.md
- install/docker/opensuse-docker-install.md
- install/docker/rhel-docker-install.md
- install/docker/sles-docker-install.md
- install/docker/ubuntu-docker-install.md
Improved the Docker installation instructions by making it clear *which* of the multiple ways of configuration Docker for Kata is the default, and that it is not necessary to do anything further if users select the automatic installation method.
Fixes: #551.
> docs: Emphasise default docker config

- how-to/privileged.md
cri-o now supports running privilged containers without passing devices
from the host to the container.
Fixes #529
> privileged: Update docs for privileged mode with crio

- Documentation-Requirements.md
Recommend the use of our own check-markdown tool to generate
TOCs.
Fixes: #582
> docs: reqs: add link/recommendation to check-markdown

- install/README.md
Now that [1] has landed, update the list of supported distros to include
Debian 10.
[1] - https://github.com/kata-containers/packaging/issues/647
Fixes: #584.
> docs: Add Debian 10 to distro table

- README.md
- use-cases/using-SPDK-vhostuser-and-kata.md
This doc includes instructions covering how to install and setup SPDK vhost-user target, construct a vhost-user-blk device based memory, configure the vhost-user-blk device to be available for kata container, and run kata container with SPDK vhost-user-blk device via docker.
Fixes: #586
> use-cases: Add initial SPDK vhost-user instructions

- Developer-Guide.md
The containerd's debug option will determine whether
the kata's log forared to containerd's log pipe or
not.
Fixes:#596
Signed-off-by: fupan.lfp <fupan.lfp@antfin.com>
> debug: add notes about how to enable debug for shimv2

- Developer-Guide.md
Add a section detailing the minimum debug you need to configure in
order to capture the kernel boot messages in the system journal.
Fixes: #593
> Developer: document how to get kernel boot messages

- Developer-Guide.md
There are two 'debug' settings in the containerd config file that
affect the shimv2 runtime log output. Add the other method to the
existing documentation, and also note that enabling full containerd
debug also affects all of containerd.
The commit also re-generates the TOC, which seems to correct a
few anomolies there.
Fixes: #596
> Dev: shimv2 logs: Elaborate on shimv2 log enabling

- use-cases/using-Intel-QAT-and-kata.md
The QAT instructions was broken after moving to a newer 4.19 kernel. Now
that the new 5.4 kernel is out, these instructions fix that.
Fixes #612
Signed-off-by: eric.adams@intel.com
> subsystem: Update QAT instructions to support 5.4 kernel

- Developer-Guide.md
The debug console can be set up with the help of both initrd or rootfs image.
Signed-off-by: Amulya Meka <amulmek1@in.ibm.com>
> docs: Change in setting up a debug console

- how-to/run-kata-with-k8s.md
CRI-O config option manage_network_ns_lifecycle is replaced with
manage_ns_lifecycle in 1.17, which determines whether we pin and remove
namespaces and manage their lifecycle.
Fixes #617
Signed-off-by: Chelsea Mafrica <chelsea.e.mafrica@intel.com>
> howto: Update deprecated CRI-O conf option

- use-cases/Nvidia-GPU-passthrough-and-Kata.md
When running docker with Nvidia GPU, the option --cap-add=ALL is required.
Fixes: #622
Signed-off-by: Jimmy Xu <jungming.xjm@antfin.com>
> use-cases: Update documentation for using Nvidia GPU with Kata

- install/sles-installation-guide.md
We need to update the SLES installation guide, as we have obs packages
for SLES 12 SP4 and not for SLES 12 SP3.
Fixes #620
> docs: Update SLES installation guide

- Release-Process.md
A basic testing can be done using jenkins pipeline.
Fixes: #631
Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>
> release: docs: Add information about package testing

- install/opensuse-installation-guide.md
This PR fixes the opensuse installation guide, it solves the issue of
having an extra empty space at the end of the distro name which is causing
a failure when we want to add the kata containers repository as we
are looking for http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/master/openSUSE_Leap_15.1%20/
which is non existing and it is giving us an error of Valid metadata not found at specified URL.
This PR replaces the URL for a correct one.
Fixes #635
> docs: Fix opensuse installation guide

- how-to/privileged.md
Add containerd and crio versions that support
`privileged_without_host_devices` behaviour.
Fixes #638
> privileged: Add containerd and crio versions.

- how-to/how-to-set-sandbox-config-kata.md
Support for passing sandbox annotations to the OCI layer was added
in containerd 1.3.0. Add this to the docs along with configuration
changes needed.
Fixes #653
> annotations: Add config documentation for containerd

- install/minikube-installation-guide.md
We only documented how to launch minikube/kata with CRI-O. It is
trivial to flip this to containerd, and that also works with kata-deploy,
so document it.
Fixes: #660
> install: minikube: add containerd details

- Developer-Guide.md
Let's add information on how to debug shimv2 when using cri-o, similarly
to what already is present with containerd.
Fixes: #672
Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>
> shimv2: Add "cri-o" debugging instructions

- how-to/how-to-use-virtio-fs-with-kata.md
Update this document to get rid of any nemu mentions.
Added comment to mention that number of containers that can be
launched may be limited by the size of `/dev/shm`.
Fixes #674
> virtiofs: Update virtiofs docs

- how-to/how-to-set-sandbox-config-kata.md
Using pod annotations requires a minimum version of v1.3.0 of containerd
to pass annotations down to kata. This is already somewhat mentioned in the
corresponding how-to, however, it can be mis-read as the minimum version of
kata-containers instead of containerd. This can cause extended and futile
troubleshooting on older distributions such as Ubuntu 16.04 which ship a
version of 1.2.x of containerd. This PR attempts to clarify this.
Fixes: #690 
Signed-off-by: Georg Kunz <georg.kunz@est.tech>
> Clarifying minimum version of containerd for annotations.

- design/architecture.md
First, most people don't care about CNM. Move that out of main doc.
Second, tc-filter is the default. Let's add a bit more background on
our usage of tc-filter (and clarify why we use this instead of macvtap).
Fixes: #692
Signed-off-by: Eric Ernst <eric.g.ernst@gmail.com>
> docs: update networking description

- Developer-Guide.md
Prior doc was out of date, referencing qemu-lite, and a repo that is not
maintained. Updated accordingly.
Fixes: #133
Signed-off-by: Eric Ernst <eric.g.ernst@gmail.com>
> dev-guide: update QEMU section for accuracy

- design/kata-api-design.md
The doc package of kata design, just list part apis of the the sandbox
management apis. This commit add the other sandbox apis to the api
tables, the file kata-api-design.md
Fixes #700
Signed-off-by: Ychau Wang <wangyongchao.bj@inspur.com>
> doc: Add the sandbox apis of kata-api-design.md

- design/virtualization.md
Referring virtio-net mentioning in the kata virtualization
documentation to the virtio-networking blog series published
and explaining how it works.
Fixes #709
Signed-off-by: Ariel Adam <aadam@redhat.com>
> docs: Adding hyperlink to virtio-net in kata documentation

- design/kata-api-design.md
- install/minikube-installation-guide.md
The command for intalling kata in minikube still using the old path of
the kata-deploy of the packaging project. This commit update the path of
the kata-deploy in the kata-containers/documentation project.
Fixes: #712
> docs: Update the paths of minikube installing kata yaml files

- design/kata-api-design.md
Sync the api from the runtime codes to the documentation. Remove
sandbox.Pause() and sandbox.Resume() apis and add some missing methods
in this table.
Fixes: #727
Signed-off-by: Ychau Wang <wangyongchao.bj@inspur.com>
> docs: update the sandbox operation API table

- design/architecture.md
CRI-O has dropped the support for trusted/untrusted workload definitions since crio 1.14 release, https://github.com/cri-o/cri-o/pull/2153/files 
This PR tries to make the user aware of this change. 
Fixes: #731 
Signed-off-by: Harshal Patil <harpatil@redhat.com>
> docs: Explicitly state that crio-1.14 onwards untrusted is not supported

- Developer-Guide.md
The systemd method of adding a debug console is not really
user friendly. Since we have added a much more straightforward
method to enable agent debug console, update developer guide to reflect
this.
Fixes #703
> docs: Update docs for enabling agent debug console

- design/kata-api-design.md
Add param to sandbox design apis doc. Update kata-api-design.md file,
the apis for the sandbox operations.
link to: https://github.com/kata-containers/documentation/issues/727
Fixes: #729
Signed-off-by: Ychau Wang <wangyongchao.bj@inspur.com>
> docs: add param to sandbox design api

- how-to/how-to-use-kata-containers-with-acrn.md
- how-to/how-to-use-virtio-mem-with-kata.md
- how-to/service-mesh.md
- install/docker/opensuse-leap-docker-install.md
- install/docker/opensuse-tumbleweed-docker-install.md
- install/installing-with-kata-doc-to-script.md
- install/opensuse-leap-installation-guide.md
- install/opensuse-tumbleweed-installation-guide.md
docs: modify the error url of logfmt
There are many error urls, which will affect the correctness of the document. I changed the error url to the correct url.
Fixes: https://github.com/kata-containers/documentation/issues/740
Signed-off-by: Cria Hu  <huyuqing@inspur.com>
> modify the error url of logfmt

- how-to/how-to-load-kernel-modules-with-kata.md
Add a link to the document listing the available annotations
Fixes: #756
Signed-off-by: Christophe de Dinechin <dinechin@redhat.com>
> docs: Add a link to document describing how to use annotations

- how-to/how-to-import-kata-logs-with-fluentd.md
- how-to/how-to-load-kernel-modules-with-kata.md
- how-to/how-to-set-sandbox-config-kata.md
- how-to/how-to-use-kata-containers-with-acrn.md
- how-to/how-to-use-virtio-mem-with-kata.md
- how-to/service-mesh.md
- install/docker/opensuse-leap-docker-install.md
- install/docker/opensuse-tumbleweed-docker-install.md
- install/installing-with-kata-doc-to-script.md
- install/opensuse-leap-installation-guide.md
- install/opensuse-tumbleweed-installation-guide.md
5ad4530 docs: Update broken link
e42025c docs: modify the error url of logfmt
c43cf9e docs: Add a link to document describing how to use annotations
f9a2173 docs: Document restricted annotations
> 1.11 doc backports

- Documentation-Requirements.md
The CI points to this documentation when there is a spelling failure, but that
document does not explain how to actually add a word to the
dictionary (althouygh it points to the tool).
Adding a link directly to the section makes it easier to follow the process.
Fixes: #768
Signed-off-by: Christophe de Dinechin <dinechin@redhat.com>
> documentation: Add a direct link to spell-checking documentation

- Developer-Guide.md
-Edited content for clarity
-Grammar-, syntax-, and spell-checking
-Corrected indentation
-Standardized lines to break at 78 characters
-Used 'Kata Containers' term consistently
Fixes #641
Signed-off-by: Doug Martin <doug.martin@intel.com>
> Developer-Guide.md editorial changes including:
